# fly.toml file generated for materias on 2022-10-17T11:08:47-04:00

app = "materias"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  SECRET="etothepiipowerplus1equals0"
DEPLOYED_URL="mongodb+srv://mbaum:mongopass1211@cluster0.c4dao92.mongodb.net/materias?retryWrites=true&w=majority"
DATABASE_URL="mongodb://localhost/materia"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
